Nos importamos pymongo y creamos una conexio con nuestro database de companias.

In [1]:
from pymongo import MongoClient
import pandas as pd

In [2]:
client = MongoClient('localhost:27017')

In [3]:
db = client.get_database("ironhack")
comp = db.get_collection("companies")

We create a projection with the data that we are interested to filter companies

For our first filter of the databases in the company, we decided to go with companies that have raised over 1M in funds, and have more than 1000 employees. We are interested in a city that has big companies that we can do partnerships with as well as a powerfull financial powerhouse to raise funding.

In [4]:
proj = {'name':1, 'offices.city' : 1, 'category_code': 1, 'total_money_raised':1, 'offices.country_code':1, 'number_of_employees':1, 'offices.latitude':1, 
        'offices.longitude': 1, 'offices.state_code': 1}

million = {'total_money_raised': {'$regex': "M"}}
billion = {'total_money_raised': {'$regex': "B"}}
both_mb = {'$or' : [million, billion]}
filtro2 = {'number_of_employees': {'$gte': 1000}}

lista_1m = list(comp.find({'$and': [both_mb, filtro2]}, proj))

In [5]:
df = pd.DataFrame(lista_1m)

In [6]:
len(df)

49

In [7]:
df.offices.items

<bound method Series.items of 0     [{'city': 'San Francisco', 'state_code': 'CA',...
1     [{'city': 'Menlo Park', 'state_code': 'CA', 'c...
2     [{'city': 'San Jose', 'state_code': 'CA', 'cou...
3     [{'city': 'San Jose', 'state_code': 'CA', 'cou...
4     [{'city': 'Sunnyvale', 'state_code': 'CA', 'co...
5     [{'city': 'Mountain View', 'state_code': 'CA',...
6     [{'city': 'Mountain View', 'state_code': 'CA',...
7     [{'city': 'San Mateo', 'state_code': 'CA', 'co...
8     [{'city': 'San Jose', 'state_code': 'CA', 'cou...
9     [{'city': 'New York', 'state_code': 'NY', 'cou...
10    [{'city': 'Henderson', 'state_code': 'NV', 'co...
11    [{'city': 'London', 'state_code': None, 'count...
12    [{'city': 'Tokyo', 'state_code': None, 'countr...
13    [{'city': None, 'state_code': None, 'country_c...
14    [{'city': 'Orem', 'state_code': 'UT', 'country...
15    [{'city': 'New York', 'state_code': 'NY', 'cou...
16    [{'city': 'San Mateo', 'state_code': 'CA', 'co...
17    [{'city': 'San Francisco', 'state_code': 'CA',...
18    [{'city': 'Los Gatos', 'state_code': 'CA', 'co...
19    [{'city': 'Mountain View', 'state_code': 'CA',...
20    [{'city': 'Beijing', 'state_code': None, 'coun...
21    [{'city': 'Philadelphia', 'state_code': 'PA', ...
22    [{'city': 'Dallas', 'state_code': 'TX', 'count...
23    [{'city': 'Buenos Aires', 'state_code': None, ...
24    [{'city': 'Luxembourg', 'state_code': None, 'c...
25    [{'city': 'Sunnyvale', 'state_code': 'CA', 'co...
26    [{'city': 'Moscow', 'state_code': None, 'count...
27    [{'city': 'Palo Alto', 'state_code': 'CA', 'co...
28    [{'city': 'Norwalk', 'state_code': 'AL', 'coun...
29    [{'city': 'Cambridge', 'state_code': 'MA', 'co...
30    [{'city': 'Gurgaon', 'state_code': None, 'coun...
31    [{'city': 'Munich', 'state_code': None, 'count...
32    [{'city': 'Tokyo', 'state_code': None, 'countr...
33    [{'city': 'Tokyo', 'state_code': None, 'countr...
34    [{'city': 'Chicago', 'state_code': 'IL', 'coun...
35    [{'city': 'Shenzen', 'state_code': None, 'coun...
36    [{'city': 'Boston', 'state_code': 'MA', 'count...
37    [{'city': 'Hyderabad', 'state_code': None, 'co...
38    [{'city': 'Beijing', 'state_code': None, 'coun...
39    [{'city': 'Ft. Lauderdale', 'state_code': 'FL'...
40    [{'city': 'Phoenix', 'state_code': 'AZ', 'coun...
41    [{'city': 'Redmond', 'state_code': 'WA', 'coun...
42    [{'city': 'Palo Alto', 'state_code': 'CA', 'co...
43    [{'city': 'SÃ£o Paulo', 'state_code': None, 'c...
44    [{'city': 'Newtown', 'state_code': 'PA', 'coun...
45    [{'city': 'Boulder', 'state_code': 'CO', 'coun...
46    [{'city': 'Falls Church', 'state_code': 'VA', ...
47    [{'city': 'Jiangxi Province', 'state_code': No...
48    [{'city': 'New Delhi', 'state_code': None, 'co...
Name: offices, dtype: object>

In [8]:
one = df.offices[9][0]['latitude']
one

40.7311317

In [9]:
dicc1 = []
for x in range(0, 49):
    dicc1.append(df.offices[x][0]['latitude'])

In [10]:
dicc2 = []
for x in range(0, 49):
    dicc2.append(df.offices[x][0]['longitude'])

In [11]:
dicc3 = []
for x in range(0, 49):
    dicc3.append(df.offices[x][0]['city'])

In [12]:
dicc4 = []
for x in range(0,49):
    dicc4.append(df.offices[x][0]['state_code'])

In [13]:
df['lat_'] = pd.DataFrame(dicc1)
df['long'] = pd.DataFrame(dicc2)
df['city'] = pd.DataFrame(dicc3)
df['state'] = pd.DataFrame(dicc4)

In [14]:
df.drop('offices', axis = 1, inplace = True)

In [15]:
df

,_id,name,category_code,number_of_employees,total_money_raised,lat_,long,city,state
0,52cdef7c4bab8bd675297d94,Twitter,social,1300,$1.16B,37.776805,-122.416924,San Francisco,CA
1,52cdef7c4bab8bd675297d8e,Facebook,social,5299,$2.43B,37.416050,-122.151801,Menlo Park,CA
2,52cdef7c4bab8bd675297d9b,eBay,web,15000,$6.7M,37.295005,-121.930035,San Jose,CA
3,52cdef7c4bab8bd675297da2,Cisco,network_hosting,63000,$2.5M,37.408802,-121.953770,San Jose,CA
4,52cdef7c4bab8bd675297da3,Yahoo!,web,13600,$6.8M,37.418531,-122.025485,Sunnyvale,CA
5,52cdef7c4bab8bd675297dba,Google,search,28000,$555M,37.421972,-122.084143,Mountain View,CA
6,52cdef7c4bab8bd675297e0c,LinkedIn,social,4800,$200M,37.423258,-122.073635,Mountain View,CA
7,52cdef7c4bab8bd675297e4d,NetSuite,enterprise,1600,$1.5M,37.536172,-122.327323,San Mateo,CA
8,52cdef7c4bab8bd675297e89,PayPal,finance,300000,$197M,37.294465,-121.927696,San Jose,CA
9,52cdef7c4bab8bd675297e96,AOL,web,8000,$1B,40.731132,-73.991931,New York,NY
10,52cdef7c4bab8bd675297efe,Zappos,web,1500,$62.8M,36.032976,-115.064859,Henderson,NV
11,52cdef7c4bab8bd675297f19,ReachLocal,advertising,1700,$68.1M,41.531550,-72.188584,London,None
12,52cdef7c4bab8bd675297fcb,Rakuten,web,10000,$42.4M,NaN,NaN,Tokyo,None
13,52cdef7c4bab8bd675297fcd,ValueClick,advertising,1112,$45M,37.090240,-95.712891,None,None
14,52cdef7c4bab8bd6752980d0,Omniture,advertising,1000,$25M,40.323902,-111.681920,Orem,UT
15,52cdef7c4bab8bd67529812e,Yodle,advertising,1000,$40M,40.742459,-73.991813,New York,NY
16,52cdef7c4bab8bd6752981d6,SuccessFactors,enterprise,1200,$35M,37.557637,-122.285714,San Mateo,CA
17,52cdef7c4bab8bd67529823b,Salesforce,enterprise,3500,$99.9M,NaN,NaN,San Francisco,CA
18,52cdef7c4bab8bd675298300,Netflix,games_video,2000,$230M,37.251420,-121.968687,Los Gatos,CA
19,52cdef7c4bab8bd67529838d,Intuit,software,8000,$6.7M,37.428373,-122.097604,Mountain View,CA
20,52cdef7c4bab8bd675298760,Baidu,search,6000,$161M,NaN,NaN,Beijing,None
21,52cdef7c4bab8bd6752987ad,Comcast,games_video,100000,$725M,39.952576,-75.165252,Philadelphia,PA
22,52cdef7c4bab8bd6752987ff,Texas Instruments,semiconductor,30175,$25.5M,32.918138,-96.752916,Dallas,TX
23,52cdef7c4bab8bd675298837,Globant,software,2800,$28M,-34.596724,-58.370890,Buenos Aires,None
24,52cdef7d4bab8bd67529891b,Spotify,music,5000,$533M,49.607295,6.121511,Luxembourg,None
25,52cdef7d4bab8bd6752989f2,Telenav,mobile,1000,$33.6M,NaN,NaN,Sunnyvale,CA
26,52cdef7d4bab8bd675298b44,Yandex,search,4000,$5.3M,NaN,NaN,Moscow,None
27,52cdef7d4bab8bd675298c30,VMware,software,13500,$369M,37.403315,-122.145981,Palo Alto,CA
28,52cdef7d4bab8bd675298ee5,Xerox,hardware,57400,$1.1B,41.256052,-82.616032,Norwalk,AL
29,52cdef7d4bab8bd675299085,MetaCarta,mobile,99999,$10M,42.362360,-71.099692,Cambridge,MA
30,52cdef7d4bab8bd675299376,Yatra online,travel,1000,$22M,28.440431,77.078919,Gurgaon,None
31,52cdef7d4bab8bd67529941a,Siemens,hardware,405000,$8.9M,NaN,NaN,Munich,None
32,52cdef7d4bab8bd67529959e,DeNA,games_video,2192,¥2.21B,NaN,NaN,Tokyo,None
33,52cdef7d4bab8bd675299928,DeNA,games_video,2192,¥2.21B,NaN,NaN,Tokyo,None
34,52cdef7d4bab8bd675299d5d,Groupon,web,10000,$1.15B,41.896516,-87.643622,Chicago,IL
35,52cdef7d4bab8bd675299e01,PCH International,hardware,5000,$77M,NaN,NaN,Shenzen,None
36,52cdef7e4bab8bd67529a30c,Sapient,enterprise,10000,$2.4M,NaN,NaN,Boston,MA
37,52cdef7e4bab8bd67529a64a,AppLabs,software,2000,$10M,44.667237,4.769483,Hyderabad,None
38,52cdef7e4bab8bd67529a956,ChinaCache,network_hosting,1257,$32M,NaN,NaN,Beijing,None
39,52cdef7e4bab8bd67529aa87,ECI Telecom,network_hosting,3000,$173M,26.187571,-80.191299,Ft. Lauderdale,FL
40,52cdef7e4bab8bd67529b03f,Perceptis,consulting,1000,$7.5M,33.357125,-111.974507,Phoenix,AZ
41,52cdef7e4bab8bd67529b11c,Concur Technologies,software,1200,$331M,51.520028,-0.651155,Redmond,WA
42,52cdef7e4bab8bd67529b5e8,MetricStream,software,1000,$65M,37.446535,-122.118794,Palo Alto,CA
43,52cdef7e4bab8bd67529b9dd,CPM Braxis,consulting,5400,$100M,-23.591042,-46.687202,SÃ£o Paulo,None
44,52cdef7e4bab8bd67529b9df,EPAM Systems,software,8100,$50M,40.225256,-74.903558,Newtown,PA
45,52cdef7f4bab8bd67529bf3f,MD-IT,software,1000,$11.1M,40.020421,-105.236011,Boulder,CO
46,52cdef7f4bab8bd67529bfe9,General Dynamics,transportation,92900,$84.9M,38.871220,-77.217416,Falls Church,VA
47,52cdef7f4bab8bd67529c2e3,JinkoSolar Holding,cleantech,1000,$35M,NaN,NaN,Jiangxi Province,None
48,52cdef7f4bab8bd67529c420,One97 Communications,mobile,1000,$35M,NaN,NaN,New Delhi,None

In [16]:
df.state.value_counts()

CA    16
NY     2
PA     2
MA     2
AL     1
FL     1
AZ     1
CO     1
VA     1
NV     1
UT     1
WA     1
TX     1
IL     1
Name: state, dtype: int64

In [17]:
df.city.value_counts()

San Jose            3
Mountain View       3
Tokyo               3
San Mateo           2
Sunnyvale           2
San Francisco       2
Palo Alto           2
New York            2
Beijing             2
Orem                1
Boston              1
Dallas              1
Ft. Lauderdale      1
Norwalk             1
Jiangxi Province    1
Munich              1
Gurgaon             1
Falls Church        1
Boulder             1
Luxembourg          1
Phoenix             1
Shenzen             1
Hyderabad           1
London              1
Philadelphia        1
Newtown             1
Los Gatos           1
Moscow              1
SÃ£o Paulo          1
Chicago             1
New Delhi           1
Henderson           1
Menlo Park          1
Cambridge           1
Redmond             1
Buenos Aires        1
Name: city, dtype: int64

In [18]:
(14 * 100) / 49

28.571428571428573

As we can see, out of the top 10 places for companies that have raised more than a million dollars, 6 of them are located in what is commonly called "The Sillicon Valley" (they account for 14 companies in a narrowed down list of 49 companies, or 28% of all companies in our list.)

From this list of top 10 places we will choose 5 locations within the Silicon Valley to continue our analysis in Four Square. They will be:
1. San Jose
2. Mountain View
3. Sunny Vale
4. Palo Alto
5. San Francisco

In [19]:
import requests
import json
from dotenv import load_dotenv
import os
import pandas as pd
load_dotenv()

True

In [20]:
#We ready up our tokens and url for 4square API calling.
tok1= os.getenv("Client_Id")
tok2= os.getenv("Client_Secret")
url_query = 'https://api.foursquare.com/v2/venues/explore'

In [21]:
#We create a list of coordinates that we want to explore using the 4square API, They are all different Areas within the Sillicon Valley
sanjose = {'type': 'Point', 'coordinates': [37.295005,-121.930035]} 
sanjose2 = {'type': 'Point', 'coordinates': [37.294465, -121.927696]}
mtview = {'type': 'Point', 'coordinates': [37.423258, -122.073635]}
sunnyvale = {'type': 'Point', 'coordinates': [37.418531, -122.025485]}
paloalto = {'type': 'Point', 'coordinates': [37.403315, -122.145981]}
sanfrancisco = {'type': 'Point', 'coordinates': [37.776805,-122.416924]}

## Parameters that Matter
1. Designers like to go to design talks and share knowledge. There must be some nearby companies that also do design.
2. 30% of the company staff have at least 1 child.
3. Developers like to be near successful tech startups that have raised at least 1 Million dollars.
4. Executives like Starbucks A LOT. Ensure there's a starbucks not too far.
5. Account managers need to travel a lot.
6. Everyone in the company is between 25 and 40, give them some place to go party.
7. The CEO is vegan.
8. If you want to make the maintenance guy happy, a basketball stadium must be around 10 Km.
9. The office dog—"Dobby" needs a hairdresser every month. Ensure there's one not too far away.

In [161]:
#We create a list of Parameters for the 4 Square Api
#We will start by exploring the party scene of our selected cities. 
params_sanjose_nightclub = {
    'client_id': tok1,
    'client_secret': tok2,
    'v' : "20200323",
    'll' : f"{sanjose.get('coordinates')[0]}, {sanjose.get('coordinates')[1]}",
    'query' : 'nightclub'
    }

params_mtview_nightclub = {
    'client_id': tok1,
    'client_secret': tok2,
    'v' : "20200323",
    'll' : f"{mtview.get('coordinates')[0]}, {mtview.get('coordinates')[1]}",
    'query' : 'nightclub'
    }
params_sunnyvale_nightclub = {
    'client_id': tok1,
    'client_secret': tok2,
    'v' : "20200323",
    'll' : f"{sunnyvale.get('coordinates')[0]}, {sunnyvale.get('coordinates')[1]}",
    'query' : 'nightclub'
    }
params_paloalto_nightclub = {
    'client_id': tok1,
    'client_secret': tok2,
    'v' : "20200323",
    'll' : f"{paloalto.get('coordinates')[0]}, {paloalto.get('coordinates')[1]}",
    'query' : 'nightclub'
    }
params_sanfrancisco_nightclub = {
    'client_id': tok1,
    'client_secret': tok2,
    'v' : "20200323",
    'll' : f"{sanfrancisco.get('coordinates')[0]}, {sanfrancisco.get('coordinates')[1]}",
    'query' : 'nightclub'
    }

# We look for Night Life in San Jose

In [23]:
sanjose_night = requests.get(url= url_query, params = params_sanjose_nightclub).json()

In [24]:
sanjose_night

{'meta': {'code': 200, 'requestId': '607b20e25474d24d9632d9c4'},
 'response': {'suggestedRadius': 2385,
  'headerLocation': 'San Jose',
  'headerFullLocation': 'San Jose',
  'headerLocationGranularity': 'city',
  'query': 'nightclub',
  'totalResults': 28,
  'suggestedBounds': {'ne': {'lat': 37.34248053679942,
    'lng': -121.88060086347674},
   'sw': {'lat': 37.31994470058854, 'lng': -121.97389999513113}},
  'groups': [{'type': 'Recommended Places',
    'name': 'recommended',
    'items': [{'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '55a1f1a9498ed390fd121249',
       'name': 'Broken Spoke',
       'location': {'lat': 37.320969056779944,
        'lng': -121.96965912551049,
        'labeledLatLngs': [{'label': 'display',
          'lat': 37.320969056779944,
          'lng': -121.96965912551049}],
        'distance': 4545,
        'cc': 'US',
        'city': 'San Jose',
        'state': 'CA',
        'country': 'United States',
        'formattedAddress': ['San Jose, CA', 'United States']},
       'categories': [{'id': '4bf58dd8d48988d11f941735',
         'name': 'Nightclub',
         'pluralName': 'Nightclubs',
         'shortName': 'Nightclub',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/nightlife/nightclub_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []}},
      'flags': {'outsideRadius': True},
      'referralId': 'e-0-55a1f1a9498ed390fd121249-0'},
     {'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '4bf8e2ff8d30d13a837e0118',
       'name': 'Milano Nightclub',
       'location': {'address': '394 S 2nd St',
        'crossStreet': 'at E. San San Salvador',
        'lat': 37.3308204655532,
        'lng': -121.8848417330974,
        'labeledLatLngs': [{'label': 'display',
          'lat': 37.3308204655532,
          'lng': -121.8848417330974}],
        'distance': 5648,
        'postalCode': '95113',
        'cc': 'US',
        'city': 'San Jose',
        'state': 'CA',
        'country': 'United States',
        'formattedAddress': ['394 S 2nd St (at E. San San Salvador)',
         'San Jose, CA 95113',
         'United States']},
       'categories': [{'id': '4bf58dd8d48988d11f941735',
         'name': 'Nightclub',
         'pluralName': 'Nightclubs',
         'shortName': 'Nightclub',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/nightlife/nightclub_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []}},
      'flags': {'outsideRadius': True},
      'referralId': 'e-0-4bf8e2ff8d30d13a837e0118-1'},
     {'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '428fcb80f964a520ec231fe3',
       'name': 'Studio 8',
       'location': {'address': '8 S 1st St',
        'crossStreet': 'at W. Santa Clara St.',
        'lat': 37.33619318376506,
        'lng': -121.89018362592803,
        'labeledLatLngs': [{'label': 'display',
          'lat': 37.33619318376506,
          'lng': -121.89018362592803}],
        'distance': 5785,
        'postalCode': '95113',
        'cc': 'US',
        'city': 'San Jose',
        'state': 'CA',
        'country': 'United States',
        'formattedAddress': ['8 S 1st St (at W. Santa Clara St.)',
         'San Jose, CA 95113',
         'United States']},
       'categories': [{'id': '4bf58dd8d48988d11f941735',
         'name': 'Nightclub',
         'pluralName': 'Nightclubs',
         'shortName': 'Nightclub',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/nightlife/nightclub_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []}},
      'flags': {'outsideRadius': True},
      'referralId': 'e-0-428fcb80f964a520ec231fe3-2'},
     {'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '4b6e5c1df964a52014ba2ce3',
       'name': 'Miami Beach Club',
       'location': {'address': '417 S 1st St',
        'crossStreet': 'at E San Salvador St',
        'lat': 37.32961215043977,
        'lng': -121.88593354158914,
        'labeledLatLngs': [{'label': 'display',
          'lat': 37.32961215043977,
          'lng': -121.88593354158914}],
        'distance': 5485,
        'postalCode': '95113',
        'cc': 'US',
        'city': 'San Jose',
        'state': 'CA',
        'country': 'United States',
        'formattedAddress': ['417 S 1st St (at E San Salvador St)',
         'San Jose, CA 95113',
         'United States']},
       'categories': [{'id': '4bf58dd8d48988d11f941735',
         'name': 'Nightclub',
         'pluralName': 'Nightclubs',
         'shortName': 'Nightclub',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/nightlife/nightclub_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []}},
      'flags': {'outsideRadius': True},
      'referralId': 'e-0-4b6e5c1df964a52014ba2ce3-3'},
     {'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '4fe404a8e4b01ed94b5d19ce',
       'name': 'Playhouse',
       'location': {'address': '81 W Santa Clara St',
        'crossStreet': 'Market',
        'lat': 37.33574382152656,
        'lng': -121.89176936025953,
        'labeledLatLngs': [{'label': 'display',
          'lat': 37.33574382152656,
          'lng': -121.89176936025953}],
        'distance': 5660,
        'postalCode': '95113',
        'cc': 'US',
        'city': 'San Jose',
        'state': 'CA',
        'country': 'United States',
        'formattedAddress': ['81 W Santa Clara St (Market)',
         'San Jose, CA 95113',
         'United States']},
       'categories': [{'id': '4bf58dd8d48988d11f941735',
         'name': 'Nightclub',
         'pluralName': 'Nightclubs',
         'shortName': 'Nightclub',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/nightlife/nightclub_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []}},
      'flags': {'outsideRadius': True},
      'referralId': 'e-0-4fe404a8e4b01ed94b5d19ce-4'},
     {'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '59248a3d9e3b650183dc2216',
       'name': '81 | Downtown San Jose Nightclub',
       'location': {'address': '81 W Santa Clara St',
        'crossStreet': 's market st.',
        'lat': 37.33579590102886,
        'lng': -121.89175486564636,
        'labeledLatLngs': [{'label': 'display',
          'lat': 37.33579590102886,
          'lng': -121.89175486564636}],
        'distance': 5666,
        'postalCode': '95113',
        'cc': 'US',
        'city': 'San Jose',
        'state': 'CA',
        'country': 'United States',
        'formattedAddress': ['81 W Santa Clara St (s market st.)',
         'San Jose, CA 95113',
         'United States']},
       'categories': [{'id': '4bf58dd8d48988d11f941735',
         'name': 'Nightclub',
         'pluralName': 'Nightclubs',
         'shortName': 'Nightclub',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/nightlife/nightclub_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []},
       'venuePage': {'id': '419559967'}},
      'flags': {'outsideRadius': True},
      'referralId': 'e-0-59248a3d9e3b650183dc2216-5'},
     {'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '59d7e89e396de00ee3b411d2',
       'name': 'Enso Nightclub',
       'location': {'address': '97 E Santa Clara St',
        'crossStreet': 'at 3rd St',
        'lat': 37.337272,
        'lng': -121.888855,
        'labeledLatLngs': [{'label': 'display',
          'lat': 37.337272,
          'lng': -121.888855}],
        'distance': 5952,
        'postalCode': '95113',
        'cc': 'US',
        'city': 'San Jose',
        'state': 'CA',
        'country': 'United States',
        'formattedAddress': ['97 E Santa Clara St (at 3rd St)',
         'San Jose, CA 95113',
         'United States']},
       'categories': [{'id': '4bf58dd8d48988d11f941735',
         'name': 'Nightclub',
         'pluralName': 'Nightclubs',
         'shortName': 'Nightclub',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/nightlife/nightclub_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []}},
      'flags': {'outsideRadius': True},
      'referralId': 'e-0-59d7e89e396de00ee3b411d2-6'},
     {'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '4a0fb2eaf964a5207e761fe3',
       'name': 'Rodeo Club',
       'location': {'address': '610 Coleman Ave',
        'crossStreet': 'at W Taylor St',
        'lat': 37.34145618060801,
        'lng': -121.90853412020036,
        'labeledLatLngs': [{'label': 'display',
          'lat': 37.34145618060801,
          'lng': -121.90853412020036},
         {'label': 'entrance', 'lat': 37.341309, 'lng': -121.908634}],
        'distance': 5510,
        'postalCode': '95110',
        'cc': 'US',
        'city': 'San Jose',
        'state': 'CA',
        'country': 'United States',
        'formattedAddress': ['610 Coleman Ave (at W Taylor St)',
         'San Jose, CA 95110',
         'United States']},
       'categories': [{'id': '4bf58dd8d48988d1e9931735',
         'name': 'Rock Club',
         'pluralName': 'Rock Clubs',
         'shortName': 'Rock Club',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/arts_entertainment/musicvenue_rockclub_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []}},
      'flags': {'outsideRadius': True},
      'referralId': 'e-0-4a0fb2eaf964a5207e761fe3-7'},
     {'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '5f180c35c6d27016aad9254e',
       'name': 'Splash Bar',
       'location': {'address': '65 Post St, San Jose, CA 95113, USA',
        'lat': 37.335037,
        'lng': -121.89088,
        'labeledLatLngs': [{'label': 'display',
          'lat': 37.335037,
          'lng': -121.89088}],
        'distance': 5645,
        'postalCode': '95113',
        'cc': 'US',
        'city': 'San Jose',
        'state': 'CA',
        'country': 'United States',
        'formattedAddress': ['65 Post St, San Jose, CA 95113, USA',
         'San Jose, CA 95113',
         'United States']},
       'categories': [{'id': '4bf58dd8d48988d1b3941735',
         'name': 'Medical School',
         'pluralName': 'Medical Schools',
         'shortName': 'Medical School',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/building/medical_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []},
       'venuePage': {'id': '584633981'}},
      'flags': {'outsideRadius': True},
      'referralId': 'e-0-5f180c35c6d27016aad9254e-8'},
     {'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '46a25cd9f964a5202c491fe3',
       'name': 'Loft Bar and Bistro',
       'location': {'address': '90 S 2nd St',
        'crossStreet': 'at E. San Fernando St.',
        'lat': 37.33515817598336,
        'lng': -121.88816284541217,
        'labeledLatLngs': [{'label': 'display',
          'lat': 37.33515817598336,
          'lng': -121.88816284541217},
         {'label': 'entrance', 'lat': 37.335093, 'lng': -121.888186}],
        'distance': 5807,
        'postalCode': '95113',
        'cc': 'US',
        'city': 'San Jose',
        'state': 'CA',
        'country': 'United States',
        'formattedAddress': ['90 S 2nd St (at E. San Fernando St.)',
         'San Jose, CA 95113',
         'United States']},
       'categories': [{'id': '4bf58dd8d48988d11f941735',
         'name': 'Nightclub',
         'pluralName': 'Nightclubs',
         'shortName': 'Nightclub',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/nightlife/nightclub_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []}},
      'flags': {'outsideRadius': True},
      'referralId': 'e-0-46a25cd9f964a5202c491fe3-9'}]}]}}

In [25]:
sj_clubs = sanjose_night.get("response").get("groups")[0].get("items")
sj_clubs

[{'reasons': {'count': 0,
   'items': [{'summary': 'This spot is popular',
     'type': 'general',
     'reasonName': 'globalInteractionReason'}]},
  'venue': {'id': '55a1f1a9498ed390fd121249',
   'name': 'Broken Spoke',
   'location': {'lat': 37.320969056779944,
    'lng': -121.96965912551049,
    'labeledLatLngs': [{'label': 'display',
      'lat': 37.320969056779944,
      'lng': -121.96965912551049}],
    'distance': 4545,
    'cc': 'US',
    'city': 'San Jose',
    'state': 'CA',
    'country': 'United States',
    'formattedAddress': ['San Jose, CA', 'United States']},
   'categories': [{'id': '4bf58dd8d48988d11f941735',
     'name': 'Nightclub',
     'pluralName': 'Nightclubs',
     'shortName': 'Nightclub',
     'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/nightlife/nightclub_',
      'suffix': '.png'},
     'primary': True}],
   'photos': {'count': 0, 'groups': []}},
  'flags': {'outsideRadius': True},
  'referralId': 'e-0-55a1f1a9498ed390fd121249-0'},
 {'reasons': {'count': 0,
   'items': [{'summary': 'This spot is popular',
     'type': 'general',
     'reasonName': 'globalInteractionReason'}]},
  'venue': {'id': '4bf8e2ff8d30d13a837e0118',
   'name': 'Milano Nightclub',
   'location': {'address': '394 S 2nd St',
    'crossStreet': 'at E. San San Salvador',
    'lat': 37.3308204655532,
    'lng': -121.8848417330974,
    'labeledLatLngs': [{'label': 'display',
      'lat': 37.3308204655532,
      'lng': -121.8848417330974}],
    'distance': 5648,
    'postalCode': '95113',
    'cc': 'US',
    'city': 'San Jose',
    'state': 'CA',
    'country': 'United States',
    'formattedAddress': ['394 S 2nd St (at E. San San Salvador)',
     'San Jose, CA 95113',
     'United States']},
   'categories': [{'id': '4bf58dd8d48988d11f941735',
     'name': 'Nightclub',
     'pluralName': 'Nightclubs',
     'shortName': 'Nightclub',
     'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/nightlife/nightclub_',
      'suffix': '.png'},
     'primary': True}],
   'photos': {'count': 0, 'groups': []}},
  'flags': {'outsideRadius': True},
  'referralId': 'e-0-4bf8e2ff8d30d13a837e0118-1'},
 {'reasons': {'count': 0,
   'items': [{'summary': 'This spot is popular',
     'type': 'general',
     'reasonName': 'globalInteractionReason'}]},
  'venue': {'id': '428fcb80f964a520ec231fe3',
   'name': 'Studio 8',
   'location': {'address': '8 S 1st St',
    'crossStreet': 'at W. Santa Clara St.',
    'lat': 37.33619318376506,
    'lng': -121.89018362592803,
    'labeledLatLngs': [{'label': 'display',
      'lat': 37.33619318376506,
      'lng': -121.89018362592803}],
    'distance': 5785,
    'postalCode': '95113',
    'cc': 'US',
    'city': 'San Jose',
    'state': 'CA',
    'country': 'United States',
    'formattedAddress': ['8 S 1st St (at W. Santa Clara St.)',
     'San Jose, CA 95113',
     'United States']},
   'categories': [{'id': '4bf58dd8d48988d11f941735',
     'name': 'Nightclub',
     'pluralName': 'Nightclubs',
     'shortName': 'Nightclub',
     'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/nightlife/nightclub_',
      'suffix': '.png'},
     'primary': True}],
   'photos': {'count': 0, 'groups': []}},
  'flags': {'outsideRadius': True},
  'referralId': 'e-0-428fcb80f964a520ec231fe3-2'},
 {'reasons': {'count': 0,
   'items': [{'summary': 'This spot is popular',
     'type': 'general',
     'reasonName': 'globalInteractionReason'}]},
  'venue': {'id': '4b6e5c1df964a52014ba2ce3',
   'name': 'Miami Beach Club',
   'location': {'address': '417 S 1st St',
    'crossStreet': 'at E San Salvador St',
    'lat': 37.32961215043977,
    'lng': -121.88593354158914,
    'labeledLatLngs': [{'label': 'display',
      'lat': 37.32961215043977,
      'lng': -121.88593354158914}],
    'distance': 5485,
    'postalCode': '95113',
    'cc': 'US',
    'city': 'San Jose',
    'state': 'CA',
    'country': 'United States',
    'formattedAddress': ['417 S 1st St (at E San Salvador St)',
     'San Jose, CA 95113',
     'United States']},
   'categories': [{'id': '4bf58dd8d48988d11f941735',
     'name': 'Nightclub',
     'pluralName': 'Nightclubs',
     'shortName': 'Nightclub',
     'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/nightlife/nightclub_',
      'suffix': '.png'},
     'primary': True}],
   'photos': {'count': 0, 'groups': []}},
  'flags': {'outsideRadius': True},
  'referralId': 'e-0-4b6e5c1df964a52014ba2ce3-3'},
 {'reasons': {'count': 0,
   'items': [{'summary': 'This spot is popular',
     'type': 'general',
     'reasonName': 'globalInteractionReason'}]},
  'venue': {'id': '4fe404a8e4b01ed94b5d19ce',
   'name': 'Playhouse',
   'location': {'address': '81 W Santa Clara St',
    'crossStreet': 'Market',
    'lat': 37.33574382152656,
    'lng': -121.89176936025953,
    'labeledLatLngs': [{'label': 'display',
      'lat': 37.33574382152656,
      'lng': -121.89176936025953}],
    'distance': 5660,
    'postalCode': '95113',
    'cc': 'US',
    'city': 'San Jose',
    'state': 'CA',
    'country': 'United States',
    'formattedAddress': ['81 W Santa Clara St (Market)',
     'San Jose, CA 95113',
     'United States']},
   'categories': [{'id': '4bf58dd8d48988d11f941735',
     'name': 'Nightclub',
     'pluralName': 'Nightclubs',
     'shortName': 'Nightclub',
     'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/nightlife/nightclub_',
      'suffix': '.png'},
     'primary': True}],
   'photos': {'count': 0, 'groups': []}},
  'flags': {'outsideRadius': True},
  'referralId': 'e-0-4fe404a8e4b01ed94b5d19ce-4'},
 {'reasons': {'count': 0,
   'items': [{'summary': 'This spot is popular',
     'type': 'general',
     'reasonName': 'globalInteractionReason'}]},
  'venue': {'id': '59248a3d9e3b650183dc2216',
   'name': '81 | Downtown San Jose Nightclub',
   'location': {'address': '81 W Santa Clara St',
    'crossStreet': 's market st.',
    'lat': 37.33579590102886,
    'lng': -121.89175486564636,
    'labeledLatLngs': [{'label': 'display',
      'lat': 37.33579590102886,
      'lng': -121.89175486564636}],
    'distance': 5666,
    'postalCode': '95113',
    'cc': 'US',
    'city': 'San Jose',
    'state': 'CA',
    'country': 'United States',
    'formattedAddress': ['81 W Santa Clara St (s market st.)',
     'San Jose, CA 95113',
     'United States']},
   'categories': [{'id': '4bf58dd8d48988d11f941735',
     'name': 'Nightclub',
     'pluralName': 'Nightclubs',
     'shortName': 'Nightclub',
     'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/nightlife/nightclub_',
      'suffix': '.png'},
     'primary': True}],
   'photos': {'count': 0, 'groups': []},
   'venuePage': {'id': '419559967'}},
  'flags': {'outsideRadius': True},
  'referralId': 'e-0-59248a3d9e3b650183dc2216-5'},
 {'reasons': {'count': 0,
   'items': [{'summary': 'This spot is popular',
     'type': 'general',
     'reasonName': 'globalInteractionReason'}]},
  'venue': {'id': '59d7e89e396de00ee3b411d2',
   'name': 'Enso Nightclub',
   'location': {'address': '97 E Santa Clara St',
    'crossStreet': 'at 3rd St',
    'lat': 37.337272,
    'lng': -121.888855,
    'labeledLatLngs': [{'label': 'display',
      'lat': 37.337272,
      'lng': -121.888855}],
    'distance': 5952,
    'postalCode': '95113',
    'cc': 'US',
    'city': 'San Jose',
    'state': 'CA',
    'country': 'United States',
    'formattedAddress': ['97 E Santa Clara St (at 3rd St)',
     'San Jose, CA 95113',
     'United States']},
   'categories': [{'id': '4bf58dd8d48988d11f941735',
     'name': 'Nightclub',
     'pluralName': 'Nightclubs',
     'shortName': 'Nightclub',
     'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/nightlife/nightclub_',
      'suffix': '.png'},
     'primary': True}],
   'photos': {'count': 0, 'groups': []}},
  'flags': {'outsideRadius': True},
  'referralId': 'e-0-59d7e89e396de00ee3b411d2-6'},
 {'reasons': {'count': 0,
   'items': [{'summary': 'This spot is popular',
     'type': 'general',
     'reasonName': 'globalInteractionReason'}]},
  'venue': {'id': '4a0fb2eaf964a5207e761fe3',
   'name': 'Rodeo Club',
   'location': {'address': '610 Coleman Ave',
    'crossStreet': 'at W Taylor St',
    'lat': 37.34145618060801,
    'lng': -121.90853412020036,
    'labeledLatLngs': [{'label': 'display',
      'lat': 37.34145618060801,
      'lng': -121.90853412020036},
     {'label': 'entrance', 'lat': 37.341309, 'lng': -121.908634}],
    'distance': 5510,
    'postalCode': '95110',
    'cc': 'US',
    'city': 'San Jose',
    'state': 'CA',
    'country': 'United States',
    'formattedAddress': ['610 Coleman Ave (at W Taylor St)',
     'San Jose, CA 95110',
     'United States']},
   'categories': [{'id': '4bf58dd8d48988d1e9931735',
     'name': 'Rock Club',
     'pluralName': 'Rock Clubs',
     'shortName': 'Rock Club',
     'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/arts_entertainment/musicvenue_rockclub_',
      'suffix': '.png'},
     'primary': True}],
   'photos': {'count': 0, 'groups': []}},
  'flags': {'outsideRadius': True},
  'referralId': 'e-0-4a0fb2eaf964a5207e761fe3-7'},
 {'reasons': {'count': 0,
   'items': [{'summary': 'This spot is popular',
     'type': 'general',
     'reasonName': 'globalInteractionReason'}]},
  'venue': {'id': '5f180c35c6d27016aad9254e',
   'name': 'Splash Bar',
   'location': {'address': '65 Post St, San Jose, CA 95113, USA',
    'lat': 37.335037,
    'lng': -121.89088,
    'labeledLatLngs': [{'label': 'display',
      'lat': 37.335037,
      'lng': -121.89088}],
    'distance': 5645,
    'postalCode': '95113',
    'cc': 'US',
    'city': 'San Jose',
    'state': 'CA',
    'country': 'United States',
    'formattedAddress': ['65 Post St, San Jose, CA 95113, USA',
     'San Jose, CA 95113',
     'United States']},
   'categories': [{'id': '4bf58dd8d48988d1b3941735',
     'name': 'Medical School',
     'pluralName': 'Medical Schools',
     'shortName': 'Medical School',
     'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/building/medical_',
      'suffix': '.png'},
     'primary': True}],
   'photos': {'count': 0, 'groups': []},
   'venuePage': {'id': '584633981'}},
  'flags': {'outsideRadius': True},
  'referralId': 'e-0-5f180c35c6d27016aad9254e-8'},
 {'reasons': {'count': 0,
   'items': [{'summary': 'This spot is popular',
     'type': 'general',
     'reasonName': 'globalInteractionReason'}]},
  'venue': {'id': '46a25cd9f964a5202c491fe3',
   'name': 'Loft Bar and Bistro',
   'location': {'address': '90 S 2nd St',
    'crossStreet': 'at E. San Fernando St.',
    'lat': 37.33515817598336,
    'lng': -121.88816284541217,
    'labeledLatLngs': [{'label': 'display',
      'lat': 37.33515817598336,
      'lng': -121.88816284541217},
     {'label': 'entrance', 'lat': 37.335093, 'lng': -121.888186}],
    'distance': 5807,
    'postalCode': '95113',
    'cc': 'US',
    'city': 'San Jose',
    'state': 'CA',
    'country': 'United States',
    'formattedAddress': ['90 S 2nd St (at E. San Fernando St.)',
     'San Jose, CA 95113',
     'United States']},
   'categories': [{'id': '4bf58dd8d48988d11f941735',
     'name': 'Nightclub',
     'pluralName': 'Nightclubs',
     'shortName': 'Nightclub',
     'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/nightlife/nightclub_',
      'suffix': '.png'},
     'primary': True}],
   'photos': {'count': 0, 'groups': []}},
  'flags': {'outsideRadius': True},
  'referralId': 'e-0-46a25cd9f964a5202c491fe3-9'}]

In [26]:
from functools import reduce
import operator
def getFromDict(diccionario,mapa):
    return reduce(operator.getitem,mapa,diccionario)

In [27]:
mapa_nombre = ['venue', 'name']
mapa_lat = ['venue', 'location', 'lat']
mapa_long = ['venue', 'location', 'lng']

In [28]:
lista_sj_clubs = []
for dicc in sj_clubs:
    lista = {}
    lista["name"] = getFromDict(dicc, mapa_nombre)
    lista["latitud"]= getFromDict(dicc, mapa_lat)
    lista["longitud"] = getFromDict(dicc,mapa_long)
    lista_sj_clubs.append(lista)

In [29]:
lista_sj_clubs

[{'name': 'Broken Spoke',
  'latitud': 37.320969056779944,
  'longitud': -121.96965912551049},
 {'name': 'Milano Nightclub',
  'latitud': 37.3308204655532,
  'longitud': -121.8848417330974},
 {'name': 'Studio 8',
  'latitud': 37.33619318376506,
  'longitud': -121.89018362592803},
 {'name': 'Miami Beach Club',
  'latitud': 37.32961215043977,
  'longitud': -121.88593354158914},
 {'name': 'Playhouse',
  'latitud': 37.33574382152656,
  'longitud': -121.89176936025953},
 {'name': '81 | Downtown San Jose Nightclub',
  'latitud': 37.33579590102886,
  'longitud': -121.89175486564636},
 {'name': 'Enso Nightclub', 'latitud': 37.337272, 'longitud': -121.888855},
 {'name': 'Rodeo Club',
  'latitud': 37.34145618060801,
  'longitud': -121.90853412020036},
 {'name': 'Splash Bar', 'latitud': 37.335037, 'longitud': -121.89088},
 {'name': 'Loft Bar and Bistro',
  'latitud': 37.33515817598336,
  'longitud': -121.88816284541217}]

In [30]:
SJ_nightlife = pd.DataFrame(lista_sj_clubs)

In [31]:
SJ_nightlife

                               name    latitud    longitud
0                      Broken Spoke  37.320969 -121.969659
1                  Milano Nightclub  37.330820 -121.884842
2                          Studio 8  37.336193 -121.890184
3                  Miami Beach Club  37.329612 -121.885934
4                         Playhouse  37.335744 -121.891769
5  81 | Downtown San Jose Nightclub  37.335796 -121.891755
6                    Enso Nightclub  37.337272 -121.888855
7                        Rodeo Club  37.341456 -121.908534
8                        Splash Bar  37.335037 -121.890880
9               Loft Bar and Bistro  37.335158 -121.888163

In [32]:
lista_sj_clubs[0]

{'name': 'Broken Spoke',
 'latitud': 37.320969056779944,
 'longitud': -121.96965912551049}

In [95]:
documentos = []
for diccionario in lista_sj_clubs:
    temporal = {
        "name": diccionario.get("name"),
        "location": {"type": "Point", "coordinates": [diccionario.get("longitud"), diccionario.get("latitud")]}
        
    }
    documentos.append(temporal)

In [50]:
documentos[3]

{'name': 'Miami Beach Club',
 'location': {'type': 'Point',
  'coordinates': [-121.88593354158914, 37.32961215043977]}}

In [51]:
df_point = pd.DataFrame(documentos)

In [52]:
df_point

,name,location
0,Broken Spoke,"{'type': 'Point', 'coordinates': [-121.9696591..."
1,Milano Nightclub,"{'type': 'Point', 'coordinates': [-121.8848417..."
2,Studio 8,"{'type': 'Point', 'coordinates': [-121.8901836..."
3,Miami Beach Club,"{'type': 'Point', 'coordinates': [-121.8859335..."
4,Playhouse,"{'type': 'Point', 'coordinates': [-121.8917693..."
5,81 | Downtown San Jose Nightclub,"{'type': 'Point', 'coordinates': [-121.8917548..."
6,Enso Nightclub,"{'type': 'Point', 'coordinates': [-121.888855,..."
7,Rodeo Club,"{'type': 'Point', 'coordinates': [-121.9085341..."
8,Splash Bar,"{'type': 'Point', 'coordinates': [-121.89088, ..."
9,Loft Bar and Bistro,"{'type': 'Point', 'coordinates': [-121.8881628..."

In [53]:
df_point.to_json('nigthclubs_san_jose4.json', orient = 'records')

In [54]:
sj_clubs = db.get_collection("nightclubs")

In [55]:
from pymongo import GEOSPHERE
sj_clubs.create_index([("geometry", GEOSPHERE)])

'geometry_2dsphere'

In [113]:
sj_clubs.find_one({})

{'_id': ObjectId('607b22c255471685e3b839ae'),
 'name': 'Broken Spoke',
 'location': {'type': 'Point',
  'coordinates': [-121.9696591255, 37.3209690568]}}

In [57]:
paypal = [-121.9276, 37.3209]
paypal_point = {"type": "Point",  "coordinates": paypal}

In [58]:
paypal_point

{'type': 'Point', 'coordinates': [-121.9276, 37.3209]}

In [77]:
clubs_near_paypal = {"location": {"$near": {"$geometry": paypal_point, "$maxDistance": 3800}}}

In [78]:
sj_clubs_near_pp = list(sj_clubs.find(clubs_near_paypal))

In [79]:
sj_clubs_near_pp

[{'_id': ObjectId('607b22c255471685e3b839b5'),
  'name': 'Rodeo Club',
  'location': {'type': 'Point',
   'coordinates': [-121.9085341202, 37.3414561806]}},
 {'_id': ObjectId('607b22c255471685e3b839b2'),
  'name': 'Playhouse',
  'location': {'type': 'Point',
   'coordinates': [-121.8917693603, 37.3357438215]}},
 {'_id': ObjectId('607b22c255471685e3b839b3'),
  'name': '81 | Downtown San Jose Nightclub',
  'location': {'type': 'Point',
   'coordinates': [-121.8917548656, 37.335795901]}},
 {'_id': ObjectId('607b22c255471685e3b839b6'),
  'name': 'Splash Bar',
  'location': {'type': 'Point', 'coordinates': [-121.89088, 37.335037]}},
 {'_id': ObjectId('607b22c255471685e3b839ae'),
  'name': 'Broken Spoke',
  'location': {'type': 'Point',
   'coordinates': [-121.9696591255, 37.3209690568]}},
 {'_id': ObjectId('607b22c255471685e3b839b0'),
  'name': 'Studio 8',
  'location': {'type': 'Point',
   'coordinates': [-121.8901836259, 37.3361931838]}}]

6 out 9 night clubs are within 3.8km of the offices

# We look for night life in Mt. View

In [84]:
mtview_night = requests.get(url= url_query, params = params_mtview_nightclub).json()

In [85]:
mtview_clubs= mtview_night.get("response").get("groups")[0].get("items")

In [86]:
lista_mt_clubs = []
for dicc in mtview_clubs:
    lista = {}
    lista["name"] = getFromDict(dicc, mapa_nombre)
    lista["latitud"]= getFromDict(dicc, mapa_lat)
    lista["longitud"] = getFromDict(dicc,mapa_long)
    lista_mt_clubs.append(lista)

In [93]:
mt_view = pd.DataFrame(lista_mt_clubs)

In [96]:
#We create type Point coordinates with the longitude and lattitude flipped.
documentos_mtview = []
for diccionario in lista_mt_clubs:
    temporal = {
        "name": diccionario.get("name"),
        "location": {"type": "Point", "coordinates": [diccionario.get("longitud"), diccionario.get("latitud")]}
        
    }
    documentos_mtview.append(temporal)

In [168]:
documentos_mtview = pd.DataFrame(documentos_mtview)

In [184]:
documentos_mtview.to_json('nigthclubs_mt_view.json', orient = 'records')

In [171]:
google = [-122.084143, 37.421972]
google_point = {"type": "Point",  "coordinates": google}

In [178]:
clubs_near_google = {"location": {"$near": {"$geometry": google_point, "$maxDistance": 3800}}}

In [179]:
mtview_clubs_near_google = list(clubs.find(clubs_near_google))

In [180]:
mtview_clubs_near_google

[{'_id': ObjectId('607b301855471685e3b839c2'),
  'name': 'Monte Carlo',
  'location': {'type': 'Point',
   'coordinates': [-122.0795899025, 37.3935957075]}},
 {'_id': ObjectId('607b301855471685e3b839c3'),
  'name': 'Opal',
  'location': {'type': 'Point',
   'coordinates': [-122.0790864009, 37.3931397077]}},
 {'_id': ObjectId('607b301855471685e3b839cd'),
  'name': 'Opal Nightclub',
  'location': {'type': 'Point', 'coordinates': [-122.0790599, 37.3931136]}},
 {'_id': ObjectId('607b301855471685e3b839ca'),
  'name': "Alberto's Nightclub",
  'location': {'type': 'Point',
   'coordinates': [-122.0788984573, 37.3922825048]}}]

In [123]:
clubs = db.get_collection("nightclubs")

In [122]:
clubs.create_index([("geometry", GEOSPHERE)])

'geometry_2dsphere'

# We look for nightlife in SunnyVale

In [162]:
sunnyvale_night = requests.get(url= url_query, params = params_sunnyvale_nightclub).json()

In [163]:
sunnyvale_clubs= sunnyvale_night.get("response").get("groups")[0].get("items")

In [164]:
lista_sunnyvale = []
for dicc in sunnyvale_clubs:
    lista = {}
    lista["name"] = getFromDict(dicc, mapa_nombre)
    lista["latitud"]= getFromDict(dicc, mapa_lat)
    lista["longitud"] = getFromDict(dicc,mapa_long)
    lista_sunnyvale.append(lista)

In [166]:
sunnyvale = pd.DataFrame(lista_mt_clubs)
sunnyvale

                                name    latitud    longitud
0                        Monte Carlo  37.393596 -122.079590
1                               Opal  37.393140 -122.079086
2                        Pure Lounge  37.376782 -122.030112
3                Parranda Night Club  37.397079 -121.996892
4                   Milano Nightclub  37.330820 -121.884842
5   81 | Downtown San Jose Nightclub  37.335796 -121.891755
6                     Enso Nightclub  37.337272 -121.888855
7                   Fiesta Nightclub  37.282680 -121.838964
8                Alberto's Nightclub  37.392283 -122.078898
9                   Status Nightclub  37.692236 -121.901859
10                     Neo Nightclub  37.692290 -121.901836
11                    Opal Nightclub  37.393114 -122.079060
12                   Audio Nightclub  37.771378 -122.413832
13              The Uptown Nightclub  37.808598 -122.269553
14                  Temple Nightclub  37.787898 -122.397227
15               The Grand Nightclub  37.779125 -122.397692
16          Sutra Nightclub & Lounge  37.797950 -122.404346
17                George's Nightclub  37.972941 -122.524715
18   Franco's Norma Jean’s Nightclub  36.766541 -121.758537
19                  Texas night club  37.810326 -121.294266
20                      Tx Nightclub  37.810447 -121.294063
21             Crocodiles Night Club  37.670380 -121.031935
22                Paradise Nightclub  38.045090 -121.319487

In [167]:
documentos_sunnyvale = []
for diccionario in lista_sunnyvale:
    temporal = {
        "name": diccionario.get("name"),
        "location": {"type": "Point", "coordinates": [diccionario.get("longitud"), diccionario.get("latitud")]}
        
    }
    documentos_sunnyvale.append(temporal)

In [181]:
doc_sunny = pd.DataFrame(documentos_sunnyvale)

In [183]:
doc_sunny.to_json('nigthclubs_sunny.json', orient = 'records')

In [188]:
yahoo = [-122.025485, 37.418531]
yahoo_point = {"type": "Point",  "coordinates": yahoo}

In [189]:
#we create a near geoquerry on the mongo database to find clubs near yahoo at a max of 3.8 km distance
clubs_near_yahoo = {"location": {"$near": {"$geometry": yahoo_point, "$maxDistance": 3800}}}

In [190]:
sunny_clubs_near_yahoo = list(clubs.find(clubs_near_yahoo))

In [192]:
sunny_yahoo = pd.DataFrame(sunny_clubs_near_yahoo)

In [193]:
sunny_yahoo

,_id,name,location
0,607b301855471685e3b839c5,Parranda Night Club,"{'type': 'Point', 'coordinates': [-121.9968916..."
1,607b30bc55471685e3b839da,Parranda Night Club,"{'type': 'Point', 'coordinates': [-121.9968916..."

# Nightlife Palo Alto

In [ ]:
params_paloalto_nightclub = {
    'client_id': tok1,
    'client_secret': tok2,
    'v' : "20200323",
    'll' : f"{paloalto.get('coordinates')[0]}, {paloalto.get('coordinates')[1]}",
    'query' : 'nightclub'
    }

In [194]:
paloalto_night = requests.get(url= url_query, params = params_paloalto_nightclub).json()

In [195]:
paloalto_clubs= paloalto_night.get("response").get("groups")[0].get("items")

In [196]:
lista_palo = []
for dicc in paloalto_clubs:
    lista = {}
    lista["name"] = getFromDict(dicc, mapa_nombre)
    lista["latitud"]= getFromDict(dicc, mapa_lat)
    lista["longitud"] = getFromDict(dicc,mapa_long)
    lista_palo.append(lista)

In [198]:
palo_clubs = pd.DataFrame(lista_palo)

In [199]:
documentos_palo = []
for diccionario in lista_palo:
    temporal = {
        "name": diccionario.get("name"),
        "location": {"type": "Point", "coordinates": [diccionario.get("longitud"), diccionario.get("latitud")]}
        
    }
    documentos_palo.append(temporal)

In [200]:
documentos_palo

[{'name': 'Monte Carlo',
  'location': {'type': 'Point',
   'coordinates': [-122.07958990245147, 37.39359570748079]}},
 {'name': 'The Patio',
  'location': {'type': 'Point',
   'coordinates': [-122.16388813906944, 37.44517297529387]}},
 {'name': 'Melt Ultra Lounge',
  'location': {'type': 'Point',
   'coordinates': [-122.16202362348156, 37.44408262098841]}},
 {'name': 'Opal',
  'location': {'type': 'Point',
   'coordinates': [-122.07908640086832, 37.39313970774524]}},
 {'name': 'Friday Night Waltz',
  'location': {'type': 'Point',
   'coordinates': [-122.15663493754343, 37.44934147452819]}},
 {'name': "Alberto's Nightclub",
  'location': {'type': 'Point',
   'coordinates': [-122.07889845725302, 37.392282504814204]}}]

In [203]:
doc_palo = pd.DataFrame(documentos_palo)

In [204]:
doc_palo.to_json('nigthclubs_palo.json', orient = 'records')

In [ ]:
vm_ware = [-122.145981, 37.403315] 
yahoo_point = {"type": "Point",  "coordinates": yahoo}